upgrade for cinder-backup (and Ceph packages).
eayunstack/eayunstack-upgrade pull request #38
Opened 2016-10-14 09:17 UTC by zhaochao

Signed-off-by: Zhao Chao <zhaochao1984@gmail.com>

2016-10-16 11:10 UTC, huntxu requested changes

2016-10-16 11:10 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/ceph.pp
> +      'default': {
这个default应该没有引号，不然会报
`puppet/modules/eayunstack/manifests/upgrade/ceph.pp - WARNING: case statement without a default case on line 31`

2016-10-16 11:44 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/ceph.pp
> +    if ! empty($affected_services) {
另外一个问题，从26行开始到这个`if`的这部分内容，似乎可以直接放在上面那个`if $eayunstack_node_role == 'controller' {}`里面也没有问题而且看起来应该简单一点，现在看起来有点绕，不过也许还要把包的安装和定义放到文件最上面的地方才会好点。

不过这个由你决定，应该不影响最终执行的效果。

2016-10-17 03:10 UTC, zhaochao commented on puppet/modules/eayunstack/manifests/upgrade/ceph.pp
> +    if ! empty($affected_services) {
也好，我本来想着 Ceph 升级对 cinder 、glance 、nova 、qemu 什么都有影响，所以在这里用 case 区分，不过这次改动应该还好，只考虑 cinder 就可以。

2016-10-17 03:41 UTC, merged