nova: set reclaim instance interval
eayunstack/eayunstack-upgrade pull request #39
Opened 2016-10-14 10:38 UTC by fabian4

delete reclaim instance only if configure
      update reclaim instance interval time 10 days

Signed-off-by: apporc <appleorchard2000@gmail.com>

Conflicts:
	puppet/modules/eayunstack/manifests/upgrade/nova.pp

2016-10-16 11:00 UTC, huntxu requested changes

2016-10-16 11:00 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/nova.pp
>    # reclaim interval is 15 days.
注释这行没改

2016-10-17 02:04 UTC, huntxu commented
第三个commit有以下问题，基本都和引号的使用有关，
注意一下第10行那里完全不需要使用引号和花括号包围单一一个变量
puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp - WARNING: double quoted string containing no variables on line 28
puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp - WARNING: double quoted string containing no variables on line 34
puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp - WARNING: double quoted string containing no variables on line 41
puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp - WARNING: double quoted string containing no variables on line 48
puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp - WARNING: string containing only a variable on line 10
puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp - WARNING: string containing only a variable on line 10
puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp - WARNING: string containing only a variable on line 10
puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp - ERROR: single quoted string containing a variable found on line 58

2016-10-17 02:05 UTC, huntxu requested changes
第三个commit有以下问题，基本都和引号的使用有关，
注意一下第10行那里完全不需要使用引号和花括号包围单一一个变量
puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp - WARNING: double quoted string containing no variables on line 28
puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp - WARNING: double quoted string containing no variables on line 34
puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp - WARNING: double quoted string containing no variables on line 41
puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp - WARNING: double quoted string containing no variables on line 48
puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp - WARNING: string containing only a variable on line 10
puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp - WARNING: string containing only a variable on line 10
puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp - WARNING: string containing only a variable on line 10
puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp - ERROR: single quoted string containing a variable found on line 58

2016-10-17 02:05 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp
> +      file { 'consul_exec_dictory':
这是一个文件，但是命名却是"dictory"？还是是一个目录但是内容写错了？

2016-10-17 02:49 UTC, fabian4 commented on puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp
> +      file { 'consul_exec_dictory':
是一个文件，命名错误，已修改

2016-10-17 03:04 UTC, huntxu requested changes

2016-10-17 03:04 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp
> +        changes => 'set novaclient/auth_url ${auth_url}',
这里仍有错误，字符串里有变量应该有双引号
`puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp - ERROR: single quoted string containing a variable found on line 56`

2016-10-17 03:44 UTC, merged