deal with when consul cluster has only one server
eayunstack/eayunstack-upgrade pull request #84
Opened 2017-09-26 07:34 UTC by pengdake

2017-09-27 09:31 UTC, huntxu submitted a review, later dismissed

2017-09-27 09:31 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp
> +  $control_nums = size($node)
这个`$node`的命名不好，明显是个列表，应该是`$control_nodes`之类的，当然这个是之前遗留的，但最好修改一下。

2017-09-27 09:31 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp
> +  }
这个`if...else...`应该直接把`bootstrap_expect`和`storage_ips`的值先处理好，后者可以直接是一个列表，然后直接传给template就可以。不要把一个分支逻辑分散到两个地方。

2017-09-27 09:31 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp
> +  else{
这里`else`后少了个空格，puppetlint自己跑一下吧

2017-09-27 09:31 UTC, huntxu commented on puppet/modules/eayunstack/templates/consul.erb
> +	<% if @control_nums == 1%>
这里两个`if`前面都用了tab

2017-09-28 06:07 UTC, pengdake commented on puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp
> +  $control_nums = size($node)
好的

2017-09-28 06:27 UTC, pengdake commented on puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp
> +  }
你的意思是在脚本里面处理，然后模板用直接用$bootstrap_expect和$storage_ips两变量就行，不用在模板里面弄那么多条件分支了

2017-09-28 06:35 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp
> +  }
是，因为这两个地方的分支条件是一样的，所以在.pp里面根据不同分支准备好不同参数就可以了

2017-09-29 06:41 UTC, huntxu commented on puppet/modules/eayunstack/templates/consul.erb
> +	"bootstrap_expect": <%= @bootstrap_expect%>,
这里和前面一处有两个无关的空格改动，你把空格又改回tab了...

2017-10-11 02:19 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp
> +  $control_nums = size($control_nodes)
这里获取 controller 节点的数量是为了判断部署模式吧？部署模式可以通过 ```$fuel_settings['deployment_mode']``` 获取，```multinode``` 为非 HA 部署模式，只有一个 controller 节点；```ha_compact``` 为 HA 部署模式，有多个 controller 节点。

2017-10-11 02:27 UTC, pengdake commented on puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp
> +  $control_nums = size($control_nodes)
是的

2017-10-11 06:04 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp
> +  $control_nums = size($control_nodes)
感觉最好还是判断 ```deployment_mode``` 而不是 ```control_nums``` 好点，代码更易读，逻辑更清晰。

2017-10-12 05:35 UTC, pengdake commented on puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp
> +  $control_nums = size($control_nodes)
改了

2017-10-12 06:55 UTC, fabian4 commented on puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp
> +  if $deployment_mode == 'multinode' {
multinode这里不是应该是单节点吗？那这里的multinode是不是不合理？

2017-10-13 01:58 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp
> +  if $deployment_mode == 'multinode' {
multinode 对应的是有且只有一个 controller 节点的部署模式。具体哪里不合理？

2017-10-13 01:59 UTC, blkart approved these changes

2017-10-13 02:54 UTC, fabian4 commented on puppet/modules/eayunstack/manifests/upgrade/auto_evacuate/auto_evacuate.pp
> +  if $deployment_mode == 'multinode' {
这里看起来是我理解错了．

2017-10-16 04:46 UTC, huntxu requested changes

2017-10-16 04:46 UTC, huntxu commented on puppet/modules/eayunstack/templates/consul.erb
> +        "start_join": <%= @storage_ips%>,
这里有问题，puppet的template不会直接输出一个列表，如果文件格式是json这里应该是
`"start_join: [<%= @storage_ips.join(", ")>]"`

2017-10-17 11:49 UTC, blkart commented on puppet/modules/eayunstack/templates/consul.erb
> +        "start_join": <%= @storage_ips%>,
这里应该没问题，测出来的生成的文件中是 ```"start_join": ["172.16.182.2", "172.16.182.3", "172.16.182.4"]```

2017-10-20 07:54 UTC, huntxu commented on puppet/modules/eayunstack/templates/consul.erb
> +        "start_join": <%= @storage_ips%>,
嗯，看来是puppet可以输出一个列表没问题

2017-10-20 07:54 UTC, huntxu approved these changes

2017-10-20 07:56 UTC, merged