WIP:Update configs for Eayunstack Notifier service
eayunstack/eayunstack-upgrade pull request #96
Opened 2017-11-22 07:11 UTC by armstrong-liu

Update compute,glance,compute and notifier service's
config for Eayunstack Notifier service.
Signed-off-by: Armstrong Liu <vpbvmw651078@gmail.com>

2017-11-22 07:24 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +  $notification_topics = "notifications,monitor"
印象中 notifier 服务应该只用到了 monitor 的 topic 吧？ 这里建议参考类似 [fuel-plugin-neutron-ext-net](https://github.com/eayunstack/fuel-plugin-neutron-ext-net/blob/master/deployment_scripts/puppet/modules/ext_net/manifests/init.pp#L67-L74) 里的方法，通过 append 的方式只添加 monitor。

2017-11-22 07:27 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    augeas { 'update_computer_configration_for_notifier':
```computer``` -> ```compute```

2017-11-22 07:28 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +  $notification_topics = "notifications,monitor"
嗯，确实是只用了monitor这个topic，确实使用append的方式更为合适。

2017-11-22 07:30 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +        "set DEFAULT/notify_on_any_change True",
这个是新加的参数？没看到代码里有用这个配置的地方。

2017-11-22 07:31 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    Augeas['update_computer_configration_for_notifier'] {
```computer``` -> ```compute```

2017-11-22 07:31 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    augeas { 'update_computer_configration_for_notifier':
已修改。

2017-11-22 07:32 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +      ],
notify 直接放到前面的 ```augeas { 'update_computer_configration_for_notifier':{....}``` 里面就可以了。

2017-11-22 07:34 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +      enable => true,
这里是不是少了 ```ensure => running,``` ？

2017-11-22 07:34 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +        "set DEFAULT/notify_on_any_change True",
嗯，新加的参数，按照[wiki](https://oa.eayun.cn/wiki/doku.php?id=eayunstack:notification:notification&s[]=eayunstack&s[]=notifier)提供的做法修改的。

2017-11-22 07:36 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +      enable => true,
没有，eayunstack-notifier服务此时是不能够启动的，因为此时配置文件中还缺少cloud API的AK，SK，以及api_address的值。

2017-11-22 07:39 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    }
97-98 行放到 ```file { 'eayunstack-notifier':...}``` 里面去。

2017-11-22 07:41 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    }
notifier 配置文件修改需要通知 notifier 服务（重启）。

2017-11-22 07:43 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    Augeas['update_computer_configration_for_notifier'] {
已修改。

2017-11-22 07:43 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    }
102-112 行可以改成 ```Augeas[xxx] ~> Service[xxx]``` 的格式，更简单。

2017-11-22 07:43 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +      ],
已修改。

2017-11-22 07:46 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    }
由于修改notifier的配置文件时，notifier服务是没有启动的，所以此时也不需要重启该服务，具体没有启动notifier的服务是因为缺少cloud的配置。

2017-11-22 07:46 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    }
嗯，已修改。

2017-11-22 07:47 UTC, blkart commented
commit 信息里 ```Update compute,glance,compute ``` 描述不清楚，改成```nova,cinder,glance```，服务名和组件名不要混用。

2017-11-22 07:48 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    }
嗯，放到file中代码更简练一点。已修改。

2017-11-22 07:49 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +      enable => true,
后面没看到启动服务的地方，在哪里保证服务启动的？

2017-11-22 07:51 UTC, blkart requested changes
need to change

2017-11-22 07:52 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +      enable => true,
这个没办法保证eayunstack-notifier启动，因为需要手动去修改eayunstack-notifier的配置文件中有关cloud的参数，此时只能在修改成功以后手动去启动eayunstack-notifier。要是在puppet修改完配置文件后直接启动eayunstack-notifier服务，日志文件中会不断的报错。

2017-11-22 08:31 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +      enable => true,
### 三个问题：
* 装包跟服务配置没有依赖关系，这里的 ```~>``` 需要去掉，另外修改配置文件后需要通知服务重启，所以要定义修改配置文件后通知服务重启的依赖关系。如果不想在装包后立即启动服务，可以在 ```service { xxx: xxx}``` 里面添加 ```refreshonly => true```，但是 ```ensure => running``` 是必要的。
* 配置文件配置不全的情况下，服务会启动成功吗？如果服务正常启动但是一直报错，那这里是存在问题的，在服务启动的时候要检查必要参数（AK，SK，api_adddress）是否已经配置，如果没配置要报错并启动失败。
* 环境升级完成后再去手动改配置文件及手动启动服务这个不可取，那样就半自动化了。我们要实现的是全自动化。像 ```AK```、```SK``` 等这种与环境相关的配置参数，可以在环境升级前先将这些参数保存到节点上的文件中，在部署 notifier 服务时从文件中读取对应的参数(AK/SK等)对服务进行配置。这样就能实现完全自动化了。关于提前配置 AK、SK 这些参数，可以通过 [eayunstack-tools 环境变量配置功能](http://192.168.15.2/issues/10306) 来实现。

2017-11-22 09:18 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +      enable => true,
嗯，如果`AK`、`SK`等参数可以实现自动化获取时，第一、二两个问题的解决方式：
第一个问题：装包和服务依然有依赖关系，只是在`service {}`中添加`ensure => running`；
第二个问题：服务启动正常但是日志中一直报错，此时服务依然处于运行中，因为在修改配置文件成功之后，对于发送失败的消息会进行重新的发送，不影响功能。

2017-11-22 10:33 UTC, huntxu requested changes

2017-11-22 10:33 UTC, huntxu commented on puppet/modules/eayunstack/files/eayunstack-notifier
> +/var/log/eayunstack_notifier/*.log {
我不明白为什么这个文件不是rpm包里默认提供

2017-11-22 10:33 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade.pp
> +  class { 'eayunstack::upgrade::eayunstack-notifier':
这个文件的资源应该能看出来是按字母序排列的吧？

2017-11-22 10:33 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    service { $services[compute]:
这里重复定义了'openstack-nova-compute'这个资源，不需要，因为这个资源在nova的文件里已经定义了；实际使用时应该会报错才是

2017-11-22 10:33 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    service { $services[controller]:
这个也是重复定义

2017-11-22 11:13 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade.pp
> +  class { 'eayunstack::upgrade::eayunstack-notifier':
当时写的时候没有注意到，已经修改了。

2017-11-23 02:55 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +  $notification_topics = "notifications"
这里应该是 ```monitor``` 吧？

2017-11-23 02:55 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +        "set DEFAULT/notification_topics ${notification_topics}",
这里的修改也需要通过 append 的方式

2017-11-23 02:55 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +        "set DEFAULT/notification_topics ${notification_topics}",
这里的修改也需要通过 append 的方式

2017-11-23 02:55 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +  }
后面调用 ```cinder/glance/nova``` 服务的时候都没用到这里的定义，这里关于 ```$services``` 的定义可以考虑去掉，后面直接用 ```service { 'eayunstack-notifier': ...}``` 就可以了。

2017-11-23 10:38 UTC, armstrong-liu commented on puppet/modules/eayunstack/files/eayunstack-notifier
> +/var/log/eayunstack_notifier/*.log {
已根据你的建议进行调整，在RPM包里默认安装。

2017-11-23 10:38 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    service { $services[compute]:
我实际在运行时只运行了eayunstack-notifier所以这个问题没有暴露出来，现在已修改。

2017-11-23 10:39 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    service { $services[controller]:
已修改。

2017-11-23 10:40 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +  $notification_topics = "notifications"
已修改为`monitor`。

2017-11-23 10:40 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +        "set DEFAULT/notification_topics ${notification_topics}",
已修改为append的方式。

2017-11-23 10:40 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +        "set DEFAULT/notification_topics ${notification_topics}",
已修改为append的方式。

2017-11-23 10:40 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +  }
嗯，已按照你的提议的方式进行了修该。

2017-11-23 10:47 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +      Service['openstack-nova-compute']
这里 ```Augeas['update_compute_configration_for_notifier']``` 与 ``` Append_option_value <||>``` 没有依赖关系。另外这两个操作需要分别通知 ```openstack-nova-compute``` 服务。可以改成这样：
```
Augeas['update_compute_configration_for_notifier'] ~> Service['openstack-nova-compute']
Append_option_value <||> ~> Service['openstack-nova-compute']
```

2017-11-23 10:47 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    } ~>
这里不需要单独定义依赖关系，默认执行顺序就可以满足需求了。

2017-11-24 03:25 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +      Service['openstack-nova-compute']
嗯，`Augeas['update_compute_configration_for_notifier']` 与 `Append_option_value <||>`确实没有依赖关系，但是如果修改成如下形式：
```
Augeas['update_compute_configration_for_notifier'] ~> Service['openstack-nova-compute']
Append_option_value <||> ~> Service['openstack-nova-compute']
```
`openstack-nova-compute`服务需要重启两次。改成这样：
```
Augeas['update_compute_configration_for_notifier'] ~>
Append_option_value <||> ~> Service['openstack-nova-compute']
```
即去掉了`Augeas`与`Append_option_value `的依赖关系，又避免了`openstack-nova-compute`服务的二次重启。

2017-11-24 06:15 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    } ~>
已修改。

2017-11-27 02:00 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +      Service['openstack-nova-compute']
这个地方缩进再空两格

2017-11-27 02:00 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +        "set default/notification_topics monitor",
这个地方也用 ```notification_topics``` 是不是更好？

2017-11-27 02:00 UTC, blkart commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +       Service['openstack-glance-api']
这个地方是不是多了个空格？

2017-11-27 02:03 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +      Service['openstack-nova-compute']
已修改。

2017-11-27 02:10 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +        "set default/notification_topics monitor",
嗯，确实用已定义的`notification_topics`变量更好。已修改。

2017-11-27 02:10 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +       Service['openstack-glance-api']
已去掉空格。

2017-11-27 02:13 UTC, huntxu requested changes

2017-11-27 02:13 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    service { 'openstack-nova-compute':
这里仍然是重复定义了

2017-11-27 02:13 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +      Append_option_value['/etc/nova/nova.conf'] ~>
前面这两个资源之间并无依赖关系

2017-11-27 02:13 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    service { 'openstack-cinder-volume':
重复定义

2017-11-27 02:13 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    service { 'openstack-glance-api':
重复定义

2017-11-27 02:13 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    Augeas['update_notifier_configration'] ~>
`Augeas['update_notifier_configuration']`这个资源应该需要`Package['eayunstack-notifier']`提供默认配置文件？

2017-11-27 02:13 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    augeas { 'update_notifier_configration':
typo `_configuration`

2017-11-27 02:13 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +        "set default/notification_topics monitor",
为何单独这里不是用变量`$notification_topics`

2017-11-27 02:42 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +        "set default/notification_topics monitor",
已使用变量`notification_topics`

2017-11-27 02:42 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    augeas { 'update_notifier_configration':
已修改。

2017-11-27 02:52 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    service { 'openstack-nova-compute':
我去掉这个定义，然后运行所有的`class`，报错：
```
Could not find resource 'Service[openstack-nova-compute]'
```
而不去掉这个定义，运行所有的`class`，没有出现任何重复定义的错误或者警告。
测试方法：
```
puppet apply --debug --modulepath=/etc/puppet/modules/:/root/eayunstack-upgrade/puppet/modules/ /root/eayunstack-upgrade/puppet/manifests/site.pp
```

2017-11-27 03:01 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    service { 'openstack-nova-compute':
测试环境是否启用融合？这个项目目前并未考虑对融合的支持。

`openstack-nova-compute`的定义在`upgrade/nova.pp`，当节点角色为`compute`时这里会发生重复定义。

2017-11-27 03:05 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    service { 'openstack-nova-compute':
测试环境没有启用融合。`openstack-nova-compute`资源的定义，应该是局部的吧。

2017-11-27 03:30 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +      Append_option_value['/etc/nova/nova.conf'] ~>
已将这两个资源的关系修改为`order`（->）。本质上这两个资源是没有先后和依赖关系的，但是这两个资源都是修改配置文件的，而且修改完成后需要重启服务，为了避免服务的两次重启，所以给两个添加了顺序关系，两个资源都执行成功之后再通知服务进行重启。

2017-11-27 03:34 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +      Append_option_value['/etc/nova/nova.conf'] ~>
两次重启这个是你测试的结果还是你的想象？

引用 https://puppet.com/docs/puppet/5.3/lang_relationships.html#refreshing-and-notification ：
> A resource can perform its refresh action up to once per run. If it receives multiple refresh events, they’re combined and the resource only refreshes once.

2017-11-27 03:38 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +      Append_option_value['/etc/nova/nova.conf'] ~>
两次重启的情况是这样的：
```
Augeas['update_compute_configration_for_notifier'] ~> Service['openstack-nova-compute']
Append_option_value <||> ~> Service['openstack-nova-compute']
```
这样重启两次，**亲测**。
而我的意思是修改为这样的：
```
Augeas['update_compute_configration_for_notifier'] ->
Append_option_value <||> ~> Service['openstack-nova-compute']
```

2017-11-27 03:50 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +      Append_option_value['/etc/nova/nova.conf'] ~>
hunt，不好意思，确实是我的失误，我重新测试了一下，只会重启一次。

2017-11-27 03:54 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    service { 'openstack-cinder-volume':
已修改。

2017-11-27 03:54 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    service { 'openstack-glance-api':
已修改

2017-11-27 03:58 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    service { 'openstack-nova-compute':
经验证，执行所有的`class`会时报重复定义的错误：`Duplicate declaration`。已取消全部重复定义内容。谢谢。

2017-11-27 04:03 UTC, blkart approved these changes

2017-11-27 04:32 UTC, huntxu requested changes
puppet-lint complains about the following with `puppet-lint --no-documentation-check --no-80chars-check --no-variable_scope-check --no-arrow_on_right_operand_line-check ./puppet`:
> ./puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp - ERROR: class name containing a dash on line 1
> ./puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp - WARNING: double quoted string containing no variables on line 12
> ./puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp - WARNING: double quoted string containing no variables on line 25
> ./puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp - ERROR: trailing whitespace found on line 9
> ./puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp - ERROR: trailing whitespace found on line 34
> ./puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp - ERROR: trailing whitespace found on line 40
> ./puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp - ERROR: trailing whitespace found on line 41
> ./puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp - ERROR: trailing whitespace found on line 83
> ./puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp - ERROR: trailing whitespace found on line 85
> ./puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp - ERROR: trailing whitespace found on line 86

2017-11-27 04:32 UTC, huntxu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    augeas { 'update_compute_configration_for_notifier':
这里也一个typo

2017-11-27 07:23 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    augeas { 'update_compute_configration_for_notifier':
已修改。

2017-11-27 07:24 UTC, armstrong-liu commented on puppet/modules/eayunstack/manifests/upgrade/eayunstack-notifier.pp
> +    Augeas['update_notifier_configration'] ~>
`augeas`的定义中已添加`require`。

2017-11-27 07:49 UTC, huntxu approved these changes

2017-11-27 07:50 UTC, merged